### ISSUE TITLE
Better Driver support

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/gauxilium#178]
See the comment(s) on #133 and all of the below:

#166
#174
#177
#160

### Todo

Everything needs to be stripped out and made more driver aware. This will mean a lot of duplication to allow the flexibility of per driver linting.

As a first pass:

- [x] - The `statements` directory should have each driver within it. So instead of `statements/alter.ts`, it'd be `statements/mysql/alter.ts`, `statements/psql/alter.ts` etc...
- [x] - Update `barrel.ts` so it includes the statements for all drivers.
- [x] - Fallback to `mysql` as the default driver
- [x] - The `checks` directory should also have each driver in it. So instead of `checks/hungarianNotation.ts` it will be `checks/mysql/hungarianNotation.ts`. We should have a `any` directory housed in here too which runs on any driver. i.e. hungarian notation is a problem in all drivers so there's no need to duplicate it.
- [x] - Update the documentation on both the README and readthedocs
- [ ] - Add tests
    - [ ] - Fallsback to mysql if none specified
    - [x] - Performs driver specific checks if driver specified (e.g. test a create option on psql and mysql)

**Comment by joereynolds** [comment]
https://github.com/joereynolds/sql-lint/releases
